In [2]:
from pathlib import Path

import pandas as pd
import geopandas as gpd
from shapely import wkt

In [3]:
well_loc = Path('../../../../data/raw/texas/cleaned_data/lease_well_coordinates.geoparquet')
well_per_lease = Path('../../../../data/raw/texas/cleaned_data/wells_per_lease.parquet')
prod_lease_cntrd = Path('../../../../data/raw/texas/cleaned_data/tot_prod_with_lease_coord.geoparquet')
prod_disp = Path('../../../../data/raw/texas/cleaned_data/prod_per_well_approx.geoparquet')


output_folder = Path("../../../../data/raw/texas/cleaned_data/permian_only")
output_folder.mkdir(parents=True, exist_ok=True)

In [51]:
texas_wells = gpd.read_parquet(well_loc)
texas_wells.columns

Index(['oil_gas_code', 'district_no', 'lease_no', 'well_no', 'api_county_code',
       'api_unique_no', 'county_name', 'wellbore_location_code', 'api_no',
       'oil_gas_code_norm', 'district_no_norm', 'lease_no_norm', 'lease_key',
       'api8_from_components', 'api8_from_api_no', 'api8', 'longitude',
       'latitude', 'geometry', 'SOURCE_ZIP', 'SOURCE_SHP', 'well_layer_type',
       'API', 'API10', 'APINUM', 'LAT27', 'LONG27', 'LAT83', 'LONG83',
       'RELIAB', 'SYMNUM', 'WELLID'],
      dtype='str')

In [52]:
texas_wells[[ 'SOURCE_SHP', 'well_layer_type',
       'API', 'API10', 'APINUM', 'LAT27', 'LONG27', 'LAT83', 'LONG83',
       'RELIAB', 'SYMNUM', 'WELLID','longitude',
       'latitude']].head()

,SOURCE_SHP,well_layer_type,API,API10,APINUM,LAT27,LONG27,LAT83,LONG83,RELIAB,SYMNUM,WELLID,longitude,latitude
0,well049s.shp,surface,04931721,NaN,NaN,32.045054,-99.098337,32.045196,-99.098676,20,8.0,31721,-99.098679,32.045194
1,well049s.shp,surface,04932950,NaN,NaN,32.045134,-99.100918,32.045277,-99.101257,20,7.0,32950,-99.101261,32.045274
2,well049s.shp,surface,04905559,NaN,NaN,32.056034,-99.085620,32.056176,-99.085960,15,7.0,05559,-99.085963,32.056174
3,well049s.shp,surface,04905919,NaN,NaN,32.039719,-99.058929,32.039862,-99.059267,40,7.0,05919,-99.059271,32.039860
4,well049s.shp,surface,04980560,NaN,NaN,32.041534,-99.058901,32.041682,-99.059247,40,7.0,80560,-99.059242,32.041674

In [53]:
texas_wells = texas_wells.drop(columns = ['oil_gas_code','district_no','lease_no','api8_from_components', 'api8_from_api_no','api8','api_county_code',
       'api_unique_no', 'county_name', 'wellbore_location_code','oil_gas_code_norm', 'district_no_norm', 'lease_no_norm','well_layer_type',
       'API', 'API10', 'APINUM',])

In [54]:
texas_wells.head()

,well_no,api_no,lease_key,longitude,latitude,geometry,SOURCE_ZIP,SOURCE_SHP,LAT27,LONG27,LAT83,LONG83,RELIAB,SYMNUM,WELLID
0,17,04931721,O_08_00277,-99.098679,32.045194,POINT (-99.09868 32.04519),well049.zip,well049s.shp,32.045054,-99.098337,32.045196,-99.098676,20,8.0,31721
1,18,04932950,O_08_00277,-99.101261,32.045274,POINT (-99.10126 32.04527),well049.zip,well049s.shp,32.045134,-99.100918,32.045277,-99.101257,20,7.0,32950
2,1,04905559,O_08_00287,-99.085963,32.056174,POINT (-99.08596 32.05617),well049.zip,well049s.shp,32.056034,-99.085620,32.056176,-99.085960,15,7.0,05559
3,1,04905919,O_08_00291,-99.059271,32.039860,POINT (-99.05927 32.03986),well049.zip,well049s.shp,32.039719,-99.058929,32.039862,-99.059267,40,7.0,05919
4,2,04980560,O_08_00291,-99.059242,32.041674,POINT (-99.05924 32.04167),well049.zip,well049s.shp,32.041534,-99.058901,32.041682,-99.059247,40,7.0,80560

In [55]:
texas_wells.shape

(587614, 15)

In [4]:
lat_max = 34.021515
lat_min = 29.462935
long_min = -105.21988
long_max = -100.036107

In [6]:
texas_permian_wells = texas_wells.loc[
    (texas_wells["latitude"] >= lat_min) &
    (texas_wells["latitude"] <= lat_max) &
    (texas_wells["longitude"] >= long_min) &
    (texas_wells["longitude"] <= long_max)
]

del texas_wells

NameError: name 'texas_wells' is not defined

In [58]:
texas_permian_wells.head(5)

,well_no,api_no,lease_key,longitude,latitude,geometry,SOURCE_ZIP,SOURCE_SHP,LAT27,LONG27,LAT83,LONG83,RELIAB,SYMNUM,WELLID
1389,67W,13502096,O_10_00875,-102.422757,31.791135,POINT (-102.42276 31.79113),well135.zip,well135s.shp,31.791008,-102.422333,31.791135,-102.422755,30,7.0,02096
1390,68,13510238,O_10_00875,-102.426877,31.790239,POINT (-102.42688 31.79024),well135.zip,well135s.shp,31.790112,-102.426453,31.790239,-102.426874,30,4.0,10238
1391,68W,13510238,O_10_00875,-102.426877,31.790239,POINT (-102.42688 31.79024),well135.zip,well135s.shp,31.790112,-102.426453,31.790239,-102.426874,30,4.0,10238
1392,71,13502111,O_10_00875,-102.440639,31.785008,POINT (-102.44064 31.78501),well135.zip,well135s.shp,31.784881,-102.440214,31.785009,-102.440636,15,7.0,02111
1393,72,13502110,O_10_00875,-102.436435,31.786058,POINT (-102.43643 31.78606),well135.zip,well135s.shp,31.785931,-102.436011,31.786059,-102.436432,20,4.0,02110

In [59]:
texas_permian_wells.dropna(subset=["geometry"]).sample(
    min(5000, texas_permian_wells["geometry"].notna().sum()),
    random_state=42
).explore(
    tiles="CartoDB positron",
    tooltip=[
        "lease_key",
    ]
)

In [60]:
texas_permian_wells["geometry_wkt"] = texas_permian_wells.geometry.to_wkt()

texas_permian_wells.drop(columns="geometry").to_csv(output_folder/"permian_wells_with_locn_and_id.csv", index=False)

del texas_permian_wells

In [61]:
wells = pd.read_parquet(well_per_lease)
wells.columns

Index(['lease_key', 'n_wells_with_coordinates', 'lease_latitude',
       'lease_longitude'],
      dtype='str')

In [62]:
permian_wells = wells.loc[
    (wells["lease_latitude"] >= lat_min) &
    (wells["lease_latitude"] <= lat_max) &
    (wells["lease_longitude"] >= long_min) &
    (wells["lease_longitude"] <= long_max)
]

del wells

permian_wells.head()

       lease_key  n_wells_with_coordinates  lease_latitude  lease_longitude
943   O_01_02545                        10       30.269693      -100.963044
960   O_01_02592                        17       30.179265      -101.195207
1145  O_01_02969                        20       30.044926      -100.701438
1382  O_01_03407                         9       30.197596      -100.618113
1383  O_01_03408                         1       30.231753      -100.627256

In [63]:
permian_wells.to_csv(output_folder/'permian_wells_per_lease.csv', index= False)

del permian_wells

In [64]:
tot_prod = gpd.read_parquet(prod_lease_cntrd)

In [65]:
tot_prod.columns

Index(['oil_gas_code', 'district_no', 'lease_no', 'field_no',
       'lease_oil_prod_vol', 'lease_csgd_prod_vol', 'lease_csgd_tot_disp',
       'operator_no', 'operator_name', 'date', 'oil_gas_code_norm',
       'district_no_norm', 'lease_no_norm', 'lease_key',
       'n_wells_with_coordinates', 'county_name', 'lease_longitude',
       'lease_latitude', 'geometry'],
      dtype='str')

In [66]:
tot_prod = tot_prod.drop(columns = ['oil_gas_code', 'district_no', 'lease_no','oil_gas_code_norm',
       'district_no_norm', 'lease_no_norm',])

In [67]:
permian_total_prod = tot_prod.loc[
    (tot_prod["lease_latitude"] >= lat_min) &
    (tot_prod["lease_latitude"] <= lat_max) &
    (tot_prod["lease_longitude"] >= long_min) &
    (tot_prod["lease_longitude"] <= long_max)
]

del tot_prod

permian_total_prod.head()

,field_no,lease_oil_prod_vol,lease_csgd_prod_vol,lease_csgd_tot_disp,operator_no,operator_name,date,lease_key,n_wells_with_coordinates,county_name,lease_longitude,lease_latitude,geometry
26,47891475,19,705.0,705,916958,"WHITE ROCK OIL & GAS, LLC",2026-01-01,O_09_13652,5.0,TERRELL,-102.165539,30.471089,POINT (-102.16554 30.47109)
27,47891475,46,678.0,678,916958,"WHITE ROCK OIL & GAS, LLC",2026-02-01,O_09_13652,5.0,TERRELL,-102.165539,30.471089,POINT (-102.16554 30.47109)
55,38255116,67,NaN,0,386310,HILCORP ENERGY COMPANY,2026-01-01,O_10_28548,2.0,WINKLER,-103.012058,31.724526,POINT (-103.01206 31.72453)
56,38255116,77,NaN,0,386310,HILCORP ENERGY COMPANY,2026-02-01,O_10_28548,2.0,WINKLER,-103.012058,31.724526,POINT (-103.01206 31.72453)
57,38255116,36,2.0,2,386310,HILCORP ENERGY COMPANY,2026-03-01,O_10_28548,2.0,WINKLER,-103.012058,31.724526,POINT (-103.01206 31.72453)

In [68]:
permian_total_prod["geometry_wkt"] = permian_total_prod.geometry.to_wkt()


permian_total_prod.drop(columns="geometry").to_csv(output_folder/'permian_tot_prod_with_lease_coord.csv', index = 0)

In [69]:
del permian_total_prod

In [5]:
prod_per_well = gpd.read_parquet(prod_disp)
prod_per_well.columns

Index(['field_no', 'operator_no', 'operator_name', 'oil_pipeline_bbl',
       'oil_truck_bbl', 'oil_tankcar_bbl', 'oil_tank_cleaning_bbl',
       'oil_circulating_bbl', 'oil_lost_stolen_bbl', 'oil_bsw_repressure_bbl',
       'oil_legacy_bbl', 'oil_skimmed_bbl', 'oil_scrubber_bbl',
       'oil_no_disp_code_bbl', 'csgd_field_ops_fuel_mcf',
       'csgd_transmission_mcf', 'csgd_processing_plant_mcf',
       'csgd_vented_flared_mcf', 'csgd_gas_lift_mcf', 'csgd_repressure_mcf',
       'csgd_carbon_black_mcf', 'csgd_underground_storage_mcf',
       'csgd_no_disp_code_mcf', 'oil_sold_total_bbl',
       'total_vented_flared_mcf', 'date', 'lease_key', 'api8', 'well_no',
       'county_name', 'longitude', 'latitude', 'geometry'],
      dtype='str')

In [6]:
prod_per_well.date.tail(5)

54727661   2011-08-01
54727662   2011-09-01
54727663   2011-10-01
54727664   2011-11-01
54727665   2011-12-01
Name: date, dtype: datetime64[us]

In [7]:
permian_prod_disp = prod_per_well.loc[
    (prod_per_well["latitude"] >= lat_min) &
    (prod_per_well["latitude"] <= lat_max) &
    (prod_per_well["longitude"] >= long_min) &
    (prod_per_well["longitude"] <= long_max)
]

del prod_per_well

In [8]:
permian_prod_disp.head()

,field_no,operator_no,operator_name,oil_pipeline_bbl,oil_truck_bbl,oil_tankcar_bbl,oil_tank_cleaning_bbl,oil_circulating_bbl,oil_lost_stolen_bbl,oil_bsw_repressure_bbl,...,oil_sold_total_bbl,total_vented_flared_mcf,date,lease_key,api8,well_no,county_name,longitude,latitude,geometry
17,19541001,623254,ONE NICKEL OPERATING LLC,0.0,36.5,0.0,0.0,0.0,0.0,0.0,...,36.5,0.0,2026-01-01,O_10_27510,33535961,3,MITCHELL,-101.054029,32.488188,POINT (-101.05403 32.48819)
18,19541001,623254,ONE NICKEL OPERATING LLC,0.0,36.5,0.0,0.0,0.0,0.0,0.0,...,36.5,0.0,2026-01-01,O_10_27510,33535962,4,MITCHELL,-101.051599,32.488132,POINT (-101.0516 32.48813)
19,19541001,623254,ONE NICKEL OPERATING LLC,0.0,36.5,0.0,0.0,0.0,0.0,0.0,...,36.5,0.0,2026-01-01,O_10_27510,33532131,5,MITCHELL,-101.058507,32.486845,POINT (-101.05851 32.48685)
20,19541001,623254,ONE NICKEL OPERATING LLC,0.0,36.5,0.0,0.0,0.0,0.0,0.0,...,36.5,0.0,2026-01-01,O_10_27510,33532283,6,MITCHELL,-101.056137,32.487223,POINT (-101.05614 32.48722)
21,19541001,623254,ONE NICKEL OPERATING LLC,0.0,38.5,0.0,0.0,0.0,0.0,0.0,...,38.5,0.0,2026-02-01,O_10_27510,33535961,3,MITCHELL,-101.054029,32.488188,POINT (-101.05403 32.48819)

In [12]:
permian_prod_disp.lease_key.unique()

<ArrowStringArray>
['O_10_27510', 'O_10_27541', 'O_11_65820', 'O_11_69587', 'O_10_22061',
 'O_10_43486', 'O_10_40299', 'O_11_68868', 'O_09_04280', 'O_11_67293',
 ...
 'O_09_11590', 'O_11_69626', 'O_10_34787', 'O_10_41862', 'O_10_34646',
 'O_09_16475', 'O_09_16252', 'O_11_68247', 'O_11_69707', 'O_11_68597']
Length: 48723, dtype: string

In [13]:
permian_prod_disp["geometry_wkt"] = permian_prod_disp.geometry.to_wkt()


permian_prod_disp.drop(columns="geometry").to_csv(output_folder/'permian_prod_per_well_approx.csv', index = 0)

In [14]:
permian_prod_disp.columns

Index(['field_no', 'operator_no', 'operator_name', 'oil_pipeline_bbl',
       'oil_truck_bbl', 'oil_tankcar_bbl', 'oil_tank_cleaning_bbl',
       'oil_circulating_bbl', 'oil_lost_stolen_bbl', 'oil_bsw_repressure_bbl',
       'oil_legacy_bbl', 'oil_skimmed_bbl', 'oil_scrubber_bbl',
       'oil_no_disp_code_bbl', 'csgd_field_ops_fuel_mcf',
       'csgd_transmission_mcf', 'csgd_processing_plant_mcf',
       'csgd_vented_flared_mcf', 'csgd_gas_lift_mcf', 'csgd_repressure_mcf',
       'csgd_carbon_black_mcf', 'csgd_underground_storage_mcf',
       'csgd_no_disp_code_mcf', 'oil_sold_total_bbl',
       'total_vented_flared_mcf', 'date', 'lease_key', 'api8', 'well_no',
       'county_name', 'longitude', 'latitude', 'geometry', 'geometry_wkt'],
      dtype='str')

Making a smaller file droping some insignificant columns

In [15]:
permian_prod_disp = permian_prod_disp.drop(columns = ['field_no','operator_name','well_no',
       'county_name','geometry'])

In [16]:
permian_prod_disp.to_csv(output_folder/'permian_prod_per_well_approx_small.csv',index = False)

In [19]:
test_wells = permian_prod_disp[['api8','lease_key','longitude','latitude']].drop_duplicates()

In [20]:
test_wells.shape

(242479, 4)

In [21]:
test_wells.to_csv('../../../../temp/test_wells.csv')