In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import zipfile
import io

In [26]:


with zipfile.ZipFile("texas_pdq.zip") as outer_zip:
    print("Outer contents:", outer_zip.namelist())
    
    # Open the inner zip without extracting to disk
    with outer_zip.open("PDQ_DSV.zip") as inner_file:
        inner_bytes = io.BytesIO(inner_file.read())
        
        with zipfile.ZipFile(inner_bytes) as inner_zip:
            print("Inner contents:", inner_zip.namelist())
            
            i = 4
            data = inner_zip.namelist()[i]

            with inner_zip.open(data) as f:
                df = pd.read_csv(f, sep = '}')


df

Outer contents: ['PDQ_DSV.zip']
Inner contents: ['GP_COUNTY_DATA_TABLE.dsv', 'GP_DATE_RANGE_CYCLE_DATA_TABLE.dsv', 'GP_DISTRICT_DATA_TABLE.dsv', 'OG_COUNTY_CYCLE_DATA_TABLE.dsv', 'OG_COUNTY_LEASE_CYCLE_DATA_TABLE.dsv', 'OG_DISTRICT_CYCLE_DATA_TABLE.dsv', 'OG_FIELD_CYCLE_DATA_TABLE.dsv', 'OG_FIELD_DW_DATA_TABLE.dsv', 'OG_LEASE_CYCLE_DATA_TABLE.dsv', 'OG_LEASE_CYCLE_DISP_DATA_TABLE.dsv', 'OG_OPERATOR_CYCLE_DATA_TABLE.dsv', 'OG_OPERATOR_DW_DATA_TABLE.dsv', 'OG_REGULATORY_LEASE_DW_DATA_TABLE.dsv', 'OG_SUMMARY_MASTER_LARGE_DATA_TABLE.dsv', 'OG_SUMMARY_ONSHORE_LEASE_DATA_TABLE.dsv', 'OG_WELL_COMPLETION_DATA_TABLE.dsv']

/var/folders/kz/7z7d62sj31zcvz9s8c3mm0hh0000gn/T/ipykernel_11540/2241836659.py:15: DtypeWarning: Columns (0: GAS_WELL_NO, 1: DISTRICT_NAME) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f, sep = '}')

,OIL_GAS_CODE,DISTRICT_NO,LEASE_NO,CYCLE_YEAR,CYCLE_MONTH,COUNTY_NO,OPERATOR_NO,FIELD_NO,CYCLE_YEAR_MONTH,FIELD_TYPE,...,CNTY_LSE_CSGD_GAS_LIFT,CNTY_LSE_OIL_TOT_DISP,CNTY_LSE_GAS_TOT_DISP,CNTY_LSE_COND_TOT_DISP,CNTY_LSE_CSGD_TOT_DISP,DISTRICT_NAME,LEASE_NAME,OPERATOR_NAME,FIELD_NAME,COUNTY_NAME
0,G,4,206667,2026,1,47,386310,29011750,202601,CA,...,0,0,615,0,0,04,"LOPEZ, G G",HILCORP ENERGY COMPANY,"ENCINITAS, EAST (V-24)",BROOKS
1,G,4,206667,2026,2,47,386310,29011750,202602,CA,...,0,0,564,0,0,04,"LOPEZ, G G",HILCORP ENERGY COMPANY,"ENCINITAS, EAST (V-24)",BROOKS
2,G,4,206667,2026,3,47,386310,29011750,202603,CA,...,0,0,620,0,0,04,"LOPEZ, G G",HILCORP ENERGY COMPANY,"ENCINITAS, EAST (V-24)",BROOKS
3,G,4,206667,2026,4,47,386310,29011750,202604,CA,...,0,0,0,0,0,04,"LOPEZ, G G",HILCORP ENERGY COMPANY,"ENCINITAS, EAST (V-24)",BROOKS
4,G,4,206667,2026,5,47,386310,29011750,202605,CA,...,0,0,0,0,0,04,"LOPEZ, G G",HILCORP ENERGY COMPANY,"ENCINITAS, EAST (V-24)",BROOKS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76058896,O,13,24287,1993,12,197,259871,20121500,199312,R,...,0,1351,0,0,4,09,CRAWFORD - BROWN,"FALCON OIL & GAS COMPANY, INC.","CONLEY, S. (MISS.)",HARDEMAN
76058897,O,11,66587,1993,1,415,326571,82710664,199301,R,...,0,0,0,0,0,8A,"SMALLWOOD, J. D. HEIRS ""A""","GRAY, GORDON OPERATOR",SHARON RIDGE (2400),SCURRY
76058898,O,11,66587,1993,2,415,326571,82710664,199302,R,...,0,0,0,0,1,8A,"SMALLWOOD, J. D. HEIRS ""A""","GRAY, GORDON OPERATOR",SHARON RIDGE (2400),SCURRY
76058899,O,11,66587,1993,3,415,326571,82710664,199303,R,...,0,39,0,0,0,8A,"SMALLWOOD, J. D. HEIRS ""A""","GRAY, GORDON OPERATOR",SHARON RIDGE (2400),SCURRY
76058900,O,11,66587,1993,4,415,326571,82710664,199304,R,...,0,0,0,0,0,8A,"SMALLWOOD, J. D. HEIRS ""A""","GRAY, GORDON OPERATOR",SHARON RIDGE (2400),SCURRY

In [27]:
df.columns

Index(['OIL_GAS_CODE', 'DISTRICT_NO', 'LEASE_NO', 'CYCLE_YEAR', 'CYCLE_MONTH',
       'COUNTY_NO', 'OPERATOR_NO', 'FIELD_NO', 'CYCLE_YEAR_MONTH',
       'FIELD_TYPE', 'GAS_WELL_NO', 'PROD_REPORT_FILED_FLAG',
       'CNTY_LSE_OIL_PROD_VOL', 'CNTY_LSE_OIL_ALLOW',
       'CNTY_LSE_OIL_ENDING_BAL', 'CNTY_LSE_GAS_PROD_VOL',
       'CNTY_LSE_GAS_ALLOW', 'CNTY_LSE_GAS_LIFT_INJ_VOL',
       'CNTY_LSE_COND_PROD_VOL', 'CNTY_LSE_COND_LIMIT',
       'CNTY_LSE_COND_ENDING_BAL', 'CNTY_LSE_CSGD_PROD_VOL',
       'CNTY_LSE_CSGD_LIMIT', 'CNTY_LSE_CSGD_GAS_LIFT',
       'CNTY_LSE_OIL_TOT_DISP', 'CNTY_LSE_GAS_TOT_DISP',
       'CNTY_LSE_COND_TOT_DISP', 'CNTY_LSE_CSGD_TOT_DISP', 'DISTRICT_NAME',
       'LEASE_NAME', 'OPERATOR_NAME', 'FIELD_NAME', 'COUNTY_NAME'],
      dtype='str')

0 is just the names and numbers of counties. <br>
1 is useless. <br>
2 Phone number of distric offices. <br>
3 Might be useful County oil production volume for all months from 1993

In [ ]:
# Looking at OG_COUNTY_CYCLE_DATA
county_cycle =

,OLDEST_PROD_CYCLE_YEAR_MONTH,NEWEST_PROD_CYCLE_YEAR_MONTH,NEWEST_SCHED_CYCLE_YEAR_MONTH,GAS_EXTRACT_DATE,OIL_EXTRACT_DATE
0,199301,202603,202606,16-MAY-26,16-MAY-26